# 达梦数据库监控采集器多数据源配置文件
# 全局配置
listenAddress = ":9200"
metricPath = "/metrics"
logLevel = "debug"
logMaxSize = 10
logMaxBackups = 3
logMaxAge = 30
encodeConfigPwd = false

# Basic Auth配置（可选）
enableBasicAuth = false
basicAuthUsername = ""
basicAuthPassword = ""

# 采集策略配置
collectStrategy = "hybrid"  # sequential/concurrent/hybrid
maxConcurrentGroups = 3
groupTimeout = 60

# 全局超时控制设置
globalTimeoutSeconds = 1
p99LatencyTarget = 1.5
enablePartialReturn = true
latencyWindowSize = 50
# 数据源配置示例1：主库
[[datasource]]
name = "master"
description = "主库"
enabled = true
dbHost = "81.70.105.201:5236"
dbUser = "SYSDBA"
dbPwd = "Dameng123."
queryTimeout = 30
maxOpenConns = 10
maxIdleConns = 2
connMaxLifetime = 30
bigKeyDataCacheTime = 60
alarmKeyCacheTime = 5
checkSlowSQL = false
slowSqlTime = 10000
slowSqlMaxRows = 10
registerHostMetrics = false
registerDatabaseMetrics = true
registerDmhsMetrics = false
registerCustomMetrics = false
priority = 1
labels = "role=master"


## 数据源配置示例2：备库（演示用，使用相同地址）
[[datasource]]
name = "slave1"
description = "备库1"
enabled = true
dbHost = "10.77.18.91:5236"
dbUser = "SYSDBA"
dbPwd = "Dameng123."
queryTimeout = 20
maxOpenConns = 5
maxIdleConns = 1
connMaxLifetime = 20
bigKeyDataCacheTime = 30
alarmKeyCacheTime = 3
checkSlowSQL = false
registerDatabaseMetrics = true
priority = 2
labels = "role=slave"
