listenAddress = ":9200"
metricPath = "/metrics"
version = ""
logMaxSize = 10
logMaxBackups = 3
logMaxAge = 30
logLevel = "debug"
encodeConfigPwd = true
enableBasicAuth = false
basicAuthUsername = ""
basicAuthPassword = ""
collectStrategy = "hybrid"
maxConcurrentGroups = 3
groupTimeout = 60
globalTimeoutSeconds = 1
p99LatencyTarget = 1.5
enablePartialReturn = true
latencyWindowSize = 50
readOnlyMode = true

[[datasource]]
  name = "master"
  description = "主库"
  enabled = true
  dbHost = "81.70.105.201:5236"
  dbUser = "SYSDBA"
  dbPwd = "ENC(zsvHz8TN9c/S2sXY3s/Y7svHz8TNm5iZhA==)"
  queryTimeout = 30
  maxOpenConns = 10
  maxIdleConns = 2
  connMaxLifetime = 30
  bigKeyDataCacheTime = 60
  alarmKeyCacheTime = 5
  checkSlowSQL = false
  slowSqlTime = 10000
  slowSqlMaxRows = 10
  registerHostMetrics = false
  registerDatabaseMetrics = true
  registerDmhsMetrics = false
  registerCustomMetrics = false
  priority = 1
  labels = "role=master"
  customMetricsFile = "./custom_metrics.toml"

#[[datasource]]
#  name = "slave1"
#  description = "备库1"
#  enabled = true
#  dbHost = "10.77.18.91:5236"
#  dbUser = "SYSDBA"
#  dbPwd = "ENC(zsvHz8TN9c/S2sXY3s/Y0Nnc4tCS/uSTyYX5mNny85nZhfOd2dzi0JL+5Mefw/DC65eX)"
#  queryTimeout = 20
#  maxOpenConns = 5
#  maxIdleConns = 1
#  connMaxLifetime = 20
#  bigKeyDataCacheTime = 30
#  alarmKeyCacheTime = 3
#  checkSlowSQL = false
#  slowSqlTime = 10000
#  slowSqlMaxRows = 10
#  registerHostMetrics = false
#  registerDatabaseMetrics = true
#  registerDmhsMetrics = false
#  registerCustomMetrics = false
#  priority = 2
#  labels = "role=slave"
#  customMetricsFile = "./custom_metrics.toml"
