package config

const (
	QueryDBInstanceRunningInfoSqlStr = `
        SELECT /*+DAMENG_EXPORTER*/
               TO_CHAR(START_TIME,'YYYY-MM-DD HH24:MI:SS'),
               CASE STATUS$ WHEN 'OPEN' THEN '1' WHEN 'MOUNT' THEN '2' WHEN 'SUSPEND' THEN '3' ELSE '4' END AS STATUS,
               CASE MODE$ WHEN 'PRIMARY' THEN '1' WHEN 'NORMAL' THEN '2' WHEN 'STANDBY' THEN '3' ELSE '4' END AS MODE,
               (SELECT COUNT(*) FROM V$TRXWAIT) TRXNUM,
               (SELECT COUNT(*) FROM V$LOCK WHERE BLOCKED=1) DEADLOCKNUM,
               (SELECT COUNT(*) FROM V$THREADS) THREADSNUM
        FROM V$INSTANCE`

	//表空间的使用率
	QueryTablespaceInfoSqlStr = `SELECT /*+DAMENG_EXPORTER*/ F.TABLESPACE_NAME,F.FREE_SPACE   AS "FREE_SIZE",T.TOTAL_SPACE   "TOTAL_SIZE"
FROM (
SELECT TABLESPACE_NAME, ROUND(SUM(BLOCKS * (SELECT PARA_VALUE / 1024 FROM V$DM_INI WHERE PARA_NAME = 'GLOBAL_PAGE_SIZE') / 1024)) FREE_SPACE
        FROM DBA_FREE_SPACE
        GROUP BY TABLESPACE_NAME) F,
      (SELECT TABLESPACE_NAME, ROUND(SUM(BYTES / 1048576)) TOTAL_SPACE
        FROM DBA_DATA_FILES
        GROUP BY TABLESPACE_NAME
        ) T
WHERE F.TABLESPACE_NAME = T.TABLESPACE_NAME`

	//表空间数据文件
	QueryTablespaceFileSqlStr = `SELECT PATH,
            TO_CHAR(TOTAL_SIZE*PAGE) AS TOTAL_SIZE,
            TO_CHAR(FREE_SIZE*PAGE)AS FREE_SIZE,
            AUTO_EXTEND,
            NEXT_SIZE,
            MAX_SIZE
    FROM V$DATAFILE;`

	QueryDBSessionsSqlStr = "SELECT COUNT(*) FROM v$sessions"
	// 其他SQL查询...
)
