{
 "title": "DM全局告警表盘",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "DB集群发生切换",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"ClusterSwitchingOccurs\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "DB内存池使用率(>80%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"DatabaseMemoryPoolIsTooHigh\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "DB状态发生变化",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"DatabaseStateTransition\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "DB存在锁等待",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"DatabaseIsWaitingForALock\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "DB连接数过高(>80%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"DatabaseConnectionsIsTooHigh\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "DB表空间使用率(>95%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"TableSpaceUtilizationIsTooHigh\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "DB重做日志内存堆积(>80%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"DmdbmsRedoLogAccumulationTooHigh\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "DB重做日志线程数(>4096)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"DmdbmsRedoLogThreadsIsTooHigh\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "HS的进程连接异常",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"HSProcessConnectionException\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "HS的currentLogTime延迟(>5min)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"HSCurrentLogTimeTimeout\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "HS的checkPointTime延迟(>8h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"HSCheckPointTimeTimeout\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "主机失联",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"HostLostContact\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "主机Cpu使用率(>80%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"CpuUsageIsTooHigh\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "磁盘分区使用率(>90%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"HighDiskPartitionUsage\"}) or vector(0)"
    }
   ]
  }
 ]
}