{
 "title": "达梦监控面板(完整版)",
 "description": "支持多数据源、多维度标签过滤，包含准确的视图查询说明",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "环境",
    "query": {
     "query": "label_values(dmdbms_system_base_info, env)"
    }
   },
   {
    "name": "region",
    "label": "区域",
    "query": {
     "query": "label_values(dmdbms_system_base_info{env=~\"$env\"}, region)"
    }
   },
   {
    "name": "cluster",
    "label": "集群",
    "query": {
     "query": "label_values(dmdbms_system_base_info{env=~\"$env\",region=~\"$region\"}, cluster)"
    }
   },
   {
    "name": "datasource",
    "label": "数据源",
    "query": {
     "query": "label_values(dmdbms_system_base_info{env=~\"$env\",region=~\"$region\",cluster=~\"$cluster\"}, datasource)"
    }
   },
   {
    "name": "interval",
    "label": "时间间隔",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "数据源资源列表", "type": "row", "description": "展示所有数据源的基础资源信息", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "数据源资源列表",
   "type": "table",
   "description": "查询V$SYSTEMINFO的N_CPU、TOTAL_PHY_SIZE、TOTAL_VIR_SIZE、TOTAL_DISK_SIZE",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "dmdbms_system_base_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"} - 0"
    }
   ]
  },
  {
   "title": "数据源健康状态",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "dmdb_up{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    },
    {
     "expr": "dmdbms_version{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "数据源概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "备库重做日志内存堆积(备库节点)",
   "type": "stat",
   "description": "查询V$RAPPLY_SYS.task_mem_used字段",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmdbms_rapply_sys_task_mem_used{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "备库重做任务线程数(备库节点)",
   "type": "stat",
   "description": "查询V$RAPPLY_SYS视图的task_num字段",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmdbms_rapply_sys_task_num {datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(time() - dmdbms_start_time_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}) by(instance)"
    }
   ]
  },
  {
   "title": "定时作业的错误数",
   "type": "stat",
   "description": "查询SYSJOB.SYSJOBHISTORIES2和SYSJOB.SYSSTEPHISTORIES2表中ERRCODE!=0且START_TIME>=(SYSDATE-31)的记录总数",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmdbms_joblog_error_num{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "活动会话事务等待数",
   "type": "stat",
   "description": "查询SELECT COUNT(*) FROM V$TRXWAIT的记录数",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmdbms_trx_num_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "线程数",
   "type": "stat",
   "description": "查询V$THREADS视图的记录总数COUNT(*)",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmdbms_thread_num_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "数据库状态",
   "type": "stat",
   "description": "查询V$INSTANCE.STATUS$字段，OPEN=1, MOUNT=2, SUSPEND=3, 其他=4",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmdbms_status_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "归档状态",
   "type": "stat",
   "description": "查询V$ARCH_STATUS.ARCH_STATUS字段，VALID=1, INVALID=0",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmdbms_status_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "数据库授权剩余天数",
   "type": "stat",
   "description": "查询V$LICENSE.expired_date字段，计算与当前日期的差值",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmdbms_license_date{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "数据库模式",
   "type": "stat",
   "description": "查询V$INSTANCE.MODE$字段，PRIMARY=1, NORMAL=2, STANDBY=3, 其他=4",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dmdbms_mode_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "距上次Redo日志切换(秒)",
   "type": "stat",
   "description": "基于V$LOG_HISTORY，展示当前数据源距最近一次 redo 日志切换的秒数(time()-last_switch_time)。",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time() - dmdbms_redo_switch_last_time_seconds{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"})"
    }
   ]
  },
  { "title": "数据库性能监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "SQL语句类型执行情况(min)",
   "type": "timeseries",
   "description": "查询V$SYSSTAT的select/insert/delete/update/ddl statements等指标",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"select statements\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "select"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"delete statements\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"insert statements\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "insert"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"update statements\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "update"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"ddl statements\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "ddl"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"transaction total count\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "SQL解析和执行统计(min)",
   "type": "timeseries",
   "description": "查询V$SYSSTAT的解析、执行计划、读写相关统计信息",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"parse count\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "解析次数"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"hard parse count\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "硬解析次数"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"plan total count\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "执行计划总数"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"plan cache hit count\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "计划缓存命中数"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"logic read count\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "逻辑读次数"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"physical read count\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "物理读次数"
    },
    {
     "expr": "rate(dmdbms_statement_type_total{statement_name=\"physical write count\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "物理写次数"
    }
   ]
  },
  {
   "title": "数据库内存池监测",
   "type": "timeseries",
   "description": "查询V$SYSSTAT特定ID：HJ ZONE(114,115,144,145)，HAGR ZONE(116,142,143)，SORT ZONE(177,178)",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "dmdbms_memory_curr_pool_info{pool_type=\"HAGR ZONE\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}  -0",
     "legendFormat": "HAGR ZONE"
    },
    {
     "expr": "dmdbms_memory_curr_pool_info{pool_type=\"SORT ZONE\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}  -0",
     "legendFormat": "SORT ZONE"
    },
    {
     "expr": "dmdbms_memory_curr_pool_info{ pool_type=\"HJ ZONE\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}  -0",
     "legendFormat": "HJ ZONE"
    }
   ]
  },
  {
   "title": "数据字典缓存信息",
   "type": "timeseries",
   "description": "查询V$DB_CACHE视图：LRU_DISCARD(缓存满淘汰次数)、DDL_DISCARD(DDL操作淘汰次数)、DISABLED_DICT_NUM(淘汰对象总数)",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(dmdbms_dict_cache_total{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\",dict_cache_type=\"lru_discard\"}[$interval]) * 60",
     "legendFormat": "LRU淘汰次数"
    },
    {
     "expr": "rate(dmdbms_dict_cache_total{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\",dict_cache_type=\"ddl_discard\"}[$interval]) * 60",
     "legendFormat": "DDL淘汰次数"
    },
    {
     "expr": "dmdbms_dict_cache_total{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\",dict_cache_type=\"disabled_dict_num\"}",
     "legendFormat": "淘汰对象总数"
    }
   ]
  },
  {
   "title": "数据库会话状态",
   "type": "timeseries",
   "description": "查询V$SESSIONS视图，按STATE(IDLE/ACTIVE)分组统计",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "dmdbms_session_type_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}",
     "legendFormat": "{{session_type}}"
    },
    {
     "expr": "dmdbms_parameter_info{param_name=\"MAX_SESSIONS\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}",
     "legendFormat": "MAX_SESSIONS"
    }
   ]
  },
  {
   "title": "FAST缓冲池的命中率",
   "type": "timeseries",
   "description": "查询V$BUFFERPOOL WHERE NAME='FAST'，计算ROUND(SUM(RAT_HIT)/COUNT(*),4)",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dmdbms_bufferpool_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}  -0",
     "legendFormat": "FAST命中率"
    }
   ]
  },
  {
   "title": "待PURGE的事务个数",
   "type": "timeseries",
   "description": "查询V$PURGE视图的OBJ_NUM字段",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dmdbms_purge_objects_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"} ",
     "legendFormat": "待PURGE事务数"
    }
   ]
  },
  {
   "title": "数据库检查点耗时(min)",
   "type": "timeseries",
   "description": "查询V$CKPT.CKPT_TIME_USED字段，单位毫秒",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(dmdbms_ckpttime_total{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "检查点耗时(min)"
    }
   ]
  },
  {
   "title": "Redo日志切换间隔趋势",
   "type": "timeseries",
   "description": "基于V$LOG_HISTORY计算最近一次 redo 日志切换与上一条记录的间隔（秒），用于观察切换节奏变化。",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dmdbms_redo_switch_interval_seconds{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}",
     "legendFormat": "切换间隔(秒)"
    }
   ]
  },
  {
   "title": "系统事件等待统计",
   "type": "timeseries",
   "description": "查询V$SYSTEM_EVENT的EVENT、TOTAL_WAITS",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(dmdbms_system_event_waits_total{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\",event!=\"network idle wait\"}[$interval]) * 60",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "事务阻塞与死锁趋势",
   "type": "timeseries",
   "description": "事务阻塞数为查询SELECT COUNT(*) FROM V$TRXWAIT的记录数，死锁数查询SELECT COUNT(*) FROM V$DEADLOCK_HISTORY",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "dmdbms_trx_num_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}",
     "legendFormat": "事务阻塞数"
    },
    {
     "expr": "rate(dmdbms_dead_lock_num_total{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "死锁数(min)"
    }
   ]
  },
  {
   "title": "LSN推进速率(min)",
   "type": "timeseries",
   "description": "基于dmdbms_rlog_lsn_total指标，展示各类LSN每分钟推进速率",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rate(dmdbms_rlog_lsn_total{lsn_type=\"CKPT_LSN\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "CKPT_LSN"
    },
    {
     "expr": "rate(dmdbms_rlog_lsn_total{lsn_type=\"FILE_LSN\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "FILE_LSN"
    },
    {
     "expr": "rate(dmdbms_rlog_lsn_total{lsn_type=\"FLUSH_LSN\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "FLUSH_LSN"
    },
    {
     "expr": "rate(dmdbms_rlog_lsn_total{lsn_type=\"CUR_LSN\",datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}[$interval]) * 60",
     "legendFormat": "CUR_LSN"
    }
   ]
  },
  { "title": "基础信息", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "数据内存池使用情况",
   "type": "table",
   "description": "查询V$SYSSTAT特定ID的STAT_VAL值计算内存使用",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "dmdbms_memory_total_pool_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"} - 0"
    },
    {
     "expr": "dmdbms_memory_curr_pool_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"} - 0"
    },
    {
     "expr": "((dmdbms_memory_curr_pool_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}-0)/dmdbms_memory_total_pool_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}-0)*100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "数据文件详情",
   "type": "table",
   "description": "查询V$DATAFILE的PATH、TOTAL_SIZE*PAGE、FREE_SIZE*PAGE等",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "dmdbms_tablespace_file_total_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"} - 0"
    },
    {
     "expr": "dmdbms_tablespace_file_free_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"} - 0"
    },
    {
     "expr": "((dmdbms_tablespace_file_total_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"} - dmdbms_tablespace_file_free_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"})/dmdbms_tablespace_file_total_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}-0)*100"
    }
   ]
  },
  {
   "title": "表空间详情",
   "type": "table",
   "description": "联合查询DBA_DATA_FILES(总大小)和DBA_FREE_SPACE(空闲大小)，使用V$DM_INI.GLOBAL_PAGE_SIZE参数",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "dmdbms_tablespace_size_total_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"} - 0"
    },
    {
     "expr": "dmdbms_tablespace_size_free_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"} - 0"
    },
    {
     "expr": "((dmdbms_tablespace_size_total_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"} - dmdbms_tablespace_size_free_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"})/dmdbms_tablespace_size_total_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}-0)*100"
    }
   ]
  },
  {
   "title": "用户信息",
   "type": "table",
   "description": "联合查询DBA_USERS和SYSUSERS，排除SYS、SYSSSO、SYSAUDITOR用户",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "dmdbms_user_list_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "归档状态信息",
   "type": "table",
   "description": "查询V$ARCH_STATUS.ARCH_STATUS字段，VALID=1, INVALID=0",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "dmdbms_arch_status_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  { "title": "集群相关指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 } },
  {
   "title": "监视器信息",
   "type": "table",
   "description": "查询V$DMMONITOR视图的监控器连接信息",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "dmdbms_monitor_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "主库向各备库的日志发送统计信息",
   "type": "table",
   "description": "V$ARCH_SEND_INFO此视图用于在主库上查询各备库的日志发送统计信息",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "expr": "dmdbms_arch_send_detail_info{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}"
    }
   ]
  },
  {
   "title": "备库重做日志内存堆积(备库节点)",
   "type": "timeseries",
   "description": "查询V$RAPPLY_SYS.task_mem_used字段",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dmdbms_rapply_sys_task_mem_used{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}  -0",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "备库重演线程数(备库节点)",
   "type": "timeseries",
   "description": "查询V$RAPPLY_SYS视图的task_num字段",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dmdbms_rapply_sys_task_num{datasource=~\"${datasource}\",env=~\"${env:.*}\",region=~\"${region:.*}\",cluster=~\"${cluster:.*}\"}  -0",
     "legendFormat": "{{datasource}}"
    }
   ]
  }
 ]
}